#!/usr/bin/env node
// Runs wrangler for the self-hosted web host, applying your local overrides.
//
// `wrangler.jsonc` is the public template every fork and the Deploy button
// start from, so your own instance's details don't belong in it. Put them in
// a gitignored `wrangler.local.json` next to it instead:
//
//   {
//     "name": "dombot-yourname",                       // the Worker's name
//     "database_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
//     "database_name": "dombot",                       // optional
//     "vars": { "DOMBOT_AUTH": "password" },           // optional, merged
//     "routes": [{ "pattern": "dombot.example.com", "custom_domain": true }]
//   }
//
// When that file exists, every `npm run web:*` script (and the secrets
// scripts) runs wrangler against `wrangler.local.jsonc`: the template with
// your overrides applied, regenerated on each run so it never drifts from
// the template. Without it, wrangler reads the template directly, exactly
// as before.
//
//   node scripts/wrangler.mjs deploy
//   node scripts/wrangler.mjs secret put DOMBOT_SECRET

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const TEMPLATE = 'wrangler.jsonc';
const OVERRIDES = 'wrangler.local.json';
const GENERATED = 'wrangler.local.jsonc';

/** JSONC → JSON text: drops // and block comments and trailing commas,
 *  leaving string contents (URLs, `//` inside quotes) alone. */
export function stripJsonc(text) {
  let out = '';
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    const next = text[i + 1];
    if (c === '"') {
      const start = i++;
      while (i < text.length && text[i] !== '"') i += text[i] === '\\' ? 2 : 1;
      out += text.slice(start, ++i);
    } else if (c === '/' && next === '/') {
      while (i < text.length && text[i] !== '\n') i++;
    } else if (c === '/' && next === '*') {
      i = text.indexOf('*/', i + 2);
      i = i === -1 ? text.length : i + 2;
    } else {
      out += c;
      i++;
    }
  }
  return out.replace(/,(\s*[}\]])/g, '$1');
}

/** The template config with `overrides` applied. */
export function applyOverrides(template, overrides) {
  const config = structuredClone(template);
  const { name, database_id, database_name, vars, routes, ...rest } = overrides;
  if (name) config.name = name;
  const db = config.d1_databases?.[0];
  if (db && database_id) db.database_id = database_id;
  if (db && database_name) db.database_name = database_name;
  if (vars) config.vars = { ...config.vars, ...vars };
  if (routes) config.routes = routes;
  // Anything else is taken as a top-level wrangler key, verbatim.
  return { ...config, ...rest };
}

/** Extra wrangler args selecting the generated config, or [] when there
 *  are no local overrides. Writes the generated file as a side effect. */
export function localConfigArgs() {
  if (!existsSync(OVERRIDES)) return [];
  const template = JSON.parse(stripJsonc(readFileSync(TEMPLATE, 'utf8')));
  const overrides = JSON.parse(readFileSync(OVERRIDES, 'utf8'));
  const banner =
    `// GENERATED by scripts/wrangler.mjs from ${TEMPLATE} + ${OVERRIDES}.\n` +
    '// Do not edit or commit; change those files instead.\n';
  writeFileSync(
    GENERATED,
    banner +
      JSON.stringify(applyOverrides(template, overrides), null, 2) +
      '\n',
  );
  return ['-c', GENERATED];
}

/** Spawns wrangler with the local config applied. */
export function runWrangler(args, options = {}) {
  return spawnSync('npx', ['wrangler', ...args, ...localConfigArgs()], {
    stdio: 'inherit',
    ...options,
  });
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = runWrangler(process.argv.slice(2));
  process.exit(result.status ?? 1);
}
